name: hikka
services:
  worker:
    public: true
    build: .
    replicas: 1
    ports:
      - 8080
    resources:
      cpu: 900m
      memory: 2Gi
    volumes:
      - hikka:/data

volumes:
  hikka:
    driver_opts:
      size: 1Gi