name: hikka
services:
  worker:
    public: true
    build:
      context: .
      dockerfile: Dockerfile_Okteto
    replicas: 1
    ports:
      - 8080
    resources:
      cpu: 900m
      memory: 2Gi
    volumes:
      - worker:/data
 
volumes:
  worker:
    size: 1Gi
