name: hikka
services:
  worker:
    public: true
    build: .
    replicas: 1
    ports:
      - 8080
    resources:
      cpu: 900m
      memory: 2Gi
    environment:
          SESSION: $SESSION
          API_ID: $API_ID
          API_HASH: $API_HASH
          CLOUD_PASS: $CLOUD_PASS